__default__:
  jobname: "{rule}"
  nodes: 1
  ntaskspernode: 1
  cpuspertask: 1
  mempercpu: "1000mb"
  time: "5:00"
  account: "ACCOUNT"
  partition: "standard"
  mailuser: "EMAIL"
  mailtype: "BEGIN,END,FAIL"
  output: "log/%x-%j.out"

build_sce:
  cpuspertask: 1
  mempercpu: "16G"
  time: "40:00"

build_SeuratObject:
  cpuspertask: 1
  mempercpu: "16G"
  time: "40:00"


