__default__:
  jobname: "{rule}"
  nodes: 1
  ppn: 1
  pmem: "1gb"
  walltime: "5:00"
  queue: "short"
  jobout: "oe"
  outdir: "logs/{rule}"

run_SeuratObject:
  ppn: 1
  walltime: "40:00"
  pmem: "16gb"

build_sce:
  ppn: 1
  walltime: "40:00"
  pmem: "16gb"
